### ISSUE TITLE
ssl.SSLError in miniirc==1.3.2 

### ISSUE THREAD

**Issue by impredicative** [luk3yx/miniirc#20]
```
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/devuser/venv/irc-rss-feed-bot/lib/python3.7/site-packages/miniirc.py", line 496, in _handler
    irc.ctcp(hostmask[0], 'VERSION', version, reply = True)
  File "/home/devuser/venv/irc-rss-feed-bot/lib/python3.7/site-packages/miniirc.py", line 214, in ctcp
    return m(target, '\x01{}\x01'.format(' '.join(msg)), tags = tags)
  File "/home/devuser/venv/irc-rss-feed-bot/lib/python3.7/site-packages/miniirc.py", line 210, in notice
    self.quote('NOTICE',  str(target), ':' + ' '.join(msg), tags = tags)
  File "/home/devuser/venv/irc-rss-feed-bot/lib/python3.7/site-packages/miniirc.py", line 196, in quote
    self.sock.sendall(msg + b'\r\n')
  File "/usr/lib/python3.7/ssl.py", line 1015, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.7/ssl.py", line 984, in send
    return self._sslobj.write(data)
ssl.SSLError: [SSL: BAD_LENGTH] bad length (_ssl.c:2341)
```

I don't recall seeing this error before. I tried rerunning, and I didn't have the error again yet. It may not have anything to do with the changes leading to 1.3.x.

**Comment by luk3yx** [comment]
I don't think this is caused by a bug in miniirc, it may have been a broken connection (and unless there's a bug in Python it's probably not from 1.3). Did it automatically reconnect after throwing that error?

**Comment by impredicative** [comment]
I don't know. I stopped the process and restarted it. If it happens again, I will see what happens next.
